apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    sbomer-secret: sbomer-sso-clients
  name: sbomer-prepare-pom
{{ include "sbomer.labels" (list .) | indent 2 }}
spec:
  params:
    - name: operation-config
      type: string
      description: "Runtime deliverable analysis configuration"
    - name: deliverable-index
      type: string
      description: "Index to select which deliverable should the POM be generated for"
  steps:
    - name: generate
      image: {{ .Values.generator.image.repository }}:{{ .Values.generator.image.tag }}
      imagePullPolicy: {{ .Values.generator.image.pullPolicy }}
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 200m
          memory: 300Mi
      env:
        - name: SBOMER_HOST
          value: {{ include "sbomer.serviceUrl" . }}
        - name: SBOMER_PNC_HOST
          value: {{ .Values.pnc.host }}
        - name: SBOMER_PNC_PRODUCT_MAPPING
          value: {{ include "sbomer.productMapping" . }}
{{- if ne .Values.env "dev" }}
        - name: QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL
          value: {{ .Values.oidc.auth.server.url }}
        - name: QUARKUS_OIDC_CLIENT_CLIENT_ID
          value: {{ .Values.oidc.client.id }}
        - name: SBOMER_SECRET_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['sbomer-secret']
{{- end }}
        - name: APP_ENV
          value: {{ .Values.env }}

        # SBOMER_CACHE_SERVICE_HOST is set by Kubernetes for us
      script: |
        #!/usr/bin/env bash

        set -e
        set -x

        if [ x"${APP_ENV}" == "xdev" ]; then
          export QUARKUS_OIDC_CLIENT_CLIENT_ENABLED=false
        fi

        if [ -n "${SBOMER_SECRET_NAME}" ]; then
          export QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET="$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/pnc-sbomer-client.secret)"
        fi

        OPERATION_CONFIG_PATH="/workdir/operation-config.yaml"

        echo "Storing configuration in the $OPERATION_CONFIG_PATH file"
        echo "$(params.operation-config)" | tee $OPERATION_CONFIG_PATH

        mkdir -p $(workspaces.data.path)
        cd $(workspaces.data.path)

        exec /workdir/.sdkman/candidates/java/17/bin/java -Duser.home=/workdir -Xms256m -Xmx512m -jar /workdir/generator/quarkus-run.jar -v sbom auto generate-operation-pom --workdir $(workspaces.data.path)/$(context.taskRun.name) --config $OPERATION_CONFIG_PATH --index "$(params.deliverable-index)"
      volumeMounts:
        - name: secrets-workdir
          mountPath: /mnt/secrets
{{- if ne .Values.env "dev" }}
  sidecars:
    - image: quay.io/rh-newcastle/pnc-vault-secrets:1.0.1
      name: get-vault-secrets
      command:
        - /bin/bash
      args:
        - -c
        - cd /mnt/secrets;
          pnc-vault-secrets dump $(SBOMER_SECRET_NAME)-$(APP_ENV);
      env:
        - name: VAULT_ADDR
          valueFrom:
            secretKeyRef:
              name: vault-connection-info
              key: vault-address
        - name: VAULT_APP_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: vault-connection-info
              key: vault-app-role-id
        - name: VAULT_APP_SECRET_ID
          valueFrom:
            secretKeyRef:
              name: vault-connection-info
              key: vault-app-secret-id
        - name: SBOMER_SECRET_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['sbomer-secret']
        - name: APP_ENV
          value: {{ .Values.env }}
      volumeMounts:
        - name: secrets-workdir
          mountPath: /mnt/secrets
{{- end }}
  workspaces:
    - name: data
      description: Workspace used to store the prepared deliverable POMs
  volumes:
    - name: secrets-workdir
      emptyDir:
        medium: Memory
